# .github/workflows/main.yml

name: Generate Dashboard Image

on:
  # 30분마다 자동으로 실행
  schedule:
    - cron: '*/30 * * * *'
  # "Run workflow" 버튼을 눌러 수동으로 실행할 수 있게 함
  workflow_dispatch:

jobs:
  build-and-commit:
    runs-on: ubuntu-latest
    steps:
      # 1. 저장소의 최신 코드를 내려받음
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Python 환경 설정
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # 3. 필요한 라이브러리 설치
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          # Playwright가 사용할 브라우저(크롬 등)를 설치
          playwright install --with-deps

      # 4. 스크린샷 스크립트 실행
      - name: Take screenshot
        run: python screenshot.py

      # 5. 생성된 이미지를 저장소에 다시 저장(커밋 & 푸시)
      - name: Commit and push the updated image
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add dashboard.png
          # 이미지에 변경사항이 있을 때만 커밋하도록 함
          git diff --quiet --staged || git commit -m "Update dashboard image"
          git push